### ISSUE TITLE
MorePaths encountered an error during the common_setup event phase

### ISSUE THREAD

**Issue by Zothen1973** [belkorin/minecraft-MorePaths#4]
![grafik](https://user-images.githubusercontent.com/77007295/105471400-fcbe9700-5c9a-11eb-93a0-bb69d47dae4a.png)

[crash-2021-01-22_09.35.00-fml.txt](https://github.com/belkorin/minecraft-MorePaths/files/5854720/crash-2021-01-22_09.35.00-fml.txt)

**Comment by sharlin073** [comment]
Having this same issue. But strangely, it was working fine, but today I updated some other mods, and now I have this error. :(

**Comment by belkorin** [comment]
resolved
